### ISSUE TITLE
[vault-operator] Terraform install fails with "Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'"

### ISSUE THREAD

**Issue by Hejwo** [banzaicloud/bank-vaults#1059]
**Describe the bug**:
Can't install Vault Operator via Terraform helm_realese.

**Steps to reproduce the bug**:
1. Configured `banzai-stable` repository:
```
data "helm_repository" "banzaicloud-stable" {
  name = "banzaicloud-stable"
  url = "https://kubernetes-charts.banzaicloud.com"
}
```
2. Added Vault Operator installation :
```
resource "helm_release" "vault-operator" {
  chart = "vault-operator"
  name = "vault-operator"
  repository = data.helm_repository.banzaicloud-stable.name
  version = "1.3.5"

  wait = false
}
```

3. Installation fails with:
`Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'`

**Additional context**:
I've pulled `bank-vaults` repository locally and:

1. changed `vault-operator/Chart.yaml` -> `apiVersion: v2`
2. Moved dependencies section from requirements to Chart.yaml due to Helm's deprecation warning. 

It works back again,but I'm not sure if it's proper solution. 

**Environment details**:
- Kubernetes version (e.g. v1.14.10-gke.36):
- Cloud-provider/provisioner: GKE
- Helm v3.2.1
- Install method: _Terraform_ :
```
$ terraform version
Terraform v0.12.16
+ provider.google v3.22.0
+ provider.helm v1.2.1
+ provider.kubernetes v1.11.3
+ provider.null v2.1.2
```

/kind bug

**Comment by bonifaido** [comment]
Hi @Hejwo, 

this was our weak try to keep this chart both Helm2 and Helm3 compatible without ruining existing installations, but I wasn't aware some software is validating this YAML, since the chart works fine with Helm 2 and Helm 3 as well (I mean the CLI).

Can you please try adding the `validate = false` attribute to the operator's `helm_release` and see if it works with that?

https://github.com/hashicorp/terraform-provider-helm/blob/master/helm/resource_release.go#L202

In the long run, we plan to remove the Helm 2 compatibility soon, during this summer.

**Comment by Hejwo** [comment]
Hi, 
unfortunately it doesn't help. Modified release look like this:
```
resource "helm_release" "vault-operator" {
  chart = "vault-operator"
  name = "vault-operator"
  repository = "banzaicloud-stable"
  version = "1.3.5"

  wait = false
  dependency_update = true
  verify = false
}
```

and the output is:
```
Error: malformed chart or values: 
	Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'

  on main-vault.tf line 34, in resource "helm_release" "vault-operator":
  34: resource "helm_release" "vault-operator" {
```

For now we've downloaded Operator Charts and fixed them locally.
