### ISSUE TITLE
Vault keys and token in s3

### ISSUE THREAD

**Issue by gowthamsubbu** [banzaicloud/bank-vaults#108]
@bonifaido When I choose s3 to store keys and token with KMS encryption for vault, Bank-vault is able to store and retrieve the keys for unsealing. However, After deleting CRD and deployments I can still see the keys and token exist in s3.

This is causing a issue when you apply CRD and deployments for the second time with the same s3 as the storage.

Bank-Vaults log

time="2018-08-02T13:36:10Z" level=info msg="initializing vault..."
time="2018-08-02T13:36:17Z" level=info msg="initializing vault"
time="2018-08-02T13:36:17Z" level=fatal msg="error initializing vault: error before init: keystore value for 'vault-root' already exists"

Is it possible to add this feature for aws storage CRD so that it could be seamless for re-deployments.

**Comment by matyix** [comment]
@gowthamsubbu  Deleting resources from an object storage is not the job of this operator by design - and we'd like to keep it that way. As a well-accepted Vault design pattern among object store backend users (e.g. S3) the unseal keys are not managed (thus deleted) buy Vault itself. The lifecycle of an unseal key is usually the concern of different set of ops people/roles (but certainly not the operator). If you wish to reuse the same key names you have to delete yourself beforehand.

**Comment by gowthamsubbu** [comment]
@matyix Understood. Thanks.

**Comment by dudicoco** [comment]
@matyix i'm experiencing a similar issue, but when updating the vault configuration.
With the unseal storage set to k8s each configuration change which triggers a rolling update will cause the error `"error initializing vault: error before init: value for key 'vault-root' already exists"`
