### ISSUE TITLE
Operator deployed incompatible Configurer

### ISSUE THREAD

**Issue by elFarto** [banzaicloud/bank-vaults#1081]
**Describe the bug**:
While performing a routine node patching/Kubernetes upgrade on our cluster, Vault became wedged when the Operator was moved to a new worker node that it hadn't previously been deployed to. The Operator deployment was using to the 'latest' image tag (a mistake on my part), so the newest version was downloaded. 

However, because the Configurer deployment also uses the 'latest' tag and the imagePullPolicy is IfNotPresent, the old existing version was used (as it was deployed on a node where it had been previously), which didn't support a new command line parameter (I believe it was --k8s-secret-labels), which caused the Configurer to error and fail to start.

To work around this issue, I manually pulled the latest image version on each of the worker nodes.

I'm not entirely certain on the details as I was attempting to fix an unrelated issue at the time (ended up being a flannel issue), so I didn't spend much time investigating it. 

**Expected behaviour**:
The Operator should always deploy a version of the Configurer that is known to be compatible. Ideally it should use the same version that the operator is deployed with. The 'latest' tag shouldn't be used, at least not in conjunction with the IfNotPresent pull policy.

I know the version can be specified in the Vault CR, but that doesn't seem like the correct place to be specifying it. It could also lead to the same issue, with a CR pointing to a version that's not compatible, while the Operator gets upgraded.

**Steps to reproduce the bug**:
1. Deploy an old version of the vault operator, and deploy a Vault CR
2. Upgrade the Operator to the latest version
3. Note that Configurer now cannot start correctly.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.15.12
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Self-Hosted
- bank-vaults version (e.g. 0.4.17): I'm not certain of the old version, around v0.5.1 or v0.5.2, it was upgraded to v1.4.0
- Install method (e.g. helm or static manifests): static manifests

/kind bug

**Comment by bonifaido** [comment]
Hi @elFarto, sounds like a really valid concern, we have defined the bank-vaults version in the webhook chart already and it is overrideable during installation time of the chart (which is `Chart.AppVersion` if not defined otherwise), and I think this should the way forward for the operator as well, the possible config options in order:
1. The `Chart.AppVersion` is the global bank-vaults version used and deployed by the operator if not defined in the CRs.
2. This can global version can be overridden during chart installation time, and that will be used in the same way if not defined in CRs.

I will remove the default Bank-Vaults image tag from the example CRs in the repository.

Does this sound feasible to you?

**Comment by elFarto** [comment]
This isn't so much to do with the initial install of the Operator, it's the Configurer Deployment resource that the operator creates for each Vault CR. This deployment has the image hard-coded to the latest tag (unless overwritten by the Vault CR).

**Comment by bonifaido** [comment]
People usually install the operator with the helm chart, and if the chart `x.y.z` is installed, it will install the operator `x.y.z`, which is known to work together with version `x.y.z` of the bank-vaults image. If you update to the most recent version of the operator through the chart, the deployment of the configured will be recreated automatically by the operator since `x.y.z` has changed.

**Comment by elFarto** [comment]
Right, but the Configurer could also be updated to the latest version if it gets scheduled to another node that hasn't run it before, and that version may be incompatible with the Operator version. Also it may not be updated to the latest version if the image already exists on that node, it'll use whatever version happened to be pulled first.

This is due to this code which by default will always use the 'banzaicloud/bank-vaults:latest' image, and will not repull it if it exists locally:
https://github.com/banzaicloud/bank-vaults/blob/829be44781cb429d39da3b31c2e88cb2f8cdbfdc/operator/pkg/controller/vault/vault_controller.go#L1030-L1039
