### ISSUE TITLE
Auto renew TLS certificate

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#159]
The Vault TLS certificate is valid for 1 year currently, we have would like to support auto upgrading this certificate via the operator. An initial implementation has been added: https://github.com/banzaicloud/bank-vaults/tree/tls-auto-renewal

**Comment by gowthamsubbu** [comment]
@bonifaido Thanks. Appreciate your quick response. We will follow up.

**Comment by raoofm** [comment]
+1

**Comment by raoofm** [comment]
Is it still a priority? Soon users including me might start hitting the 1 year usage mark and time for renewal would be up.

**Comment by bonifaido** [comment]
We will implement it this week, hopefully. Thanks for the reminder!

**Comment by bonifaido** [comment]
Anyhow if not, if you delete the secret and kill the Vault pods a brand new certificate will be created by the operator, and killing the pods will trigger a remount (as volume).

**Comment by raoofm** [comment]
sure, thanks as always :)

**Comment by primeroz** [comment]
What is the plan on how to implement this ? 

My hope is that we can fix this and #380 at once.

The scenario is one similar to https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-customports.yaml where 2 listeners with 2 separate TLS are setup , one from the vault-operator and one from an external source.

If we approach this case as a 2 step scenario where 

**First step is refresh - Vault-operator** 
1. Internal TLS is refreshed and the secret updated by the vault-operator if the date of expire is less then Xdays. This will trigger the updated secret to be remounted in the pod
1. External TLS is refreshed independently from the vault-operator, still it will trigger the updated secret to be remoutned in the pod 

**Second step - bank-vaults sidecar SIGHUP Vault if Pod Share process Namespace is enabled ** 
1. Have bank-vaults sidecar in each pod _watch_ all secrets used by listeners in the pod ( most likely just need to watch the CRT ) and SIGHUP Vault to reload secrets
   This will require a kubernetes > 1.12 where [pod-share-process-namespace](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) is enabled by default

**Second step - operator restart the vault statefulset if Pod Share process Namespace is NOT enabled**
1. If the cluster does not support sharing process namespace the vault-operator could watch all secrets related to a vault instance and trigger a full restart of the statefulset when any of those change


I am not sure what is the _minimum_ kubernetes version we target with the vault-operator , it could be something to actually put on the readme, but considering that 1.11 is [no longer maintained](https://v1-11.docs.kubernetes.io/) it might not be too bad of an idea to target 1.12 and only support the pid sharing way of doing it.

**Comment by bonifaido** [comment]
**1st step** - I had the same plan, an annotation will be added to the secret which describes the expiry time and we just read this annotation, let's say 1 week before the expiry time the operator updates the Secret.

**2nd step** - To be honest, I wanted to just restart the Vault Pods in the StatefulSet (yearly 1 restart) by adding an annotation to the podSpec part (the same as for the TLS secret), which makes the implementation more neutral and cleaner, because in this way we don't have to put extra logic into the bank-vaults sidecar and operator (guessing Kubernetes versions, detecting that the TLS secret has changed from the sidecar, signaling to Vault, and additional glue in the operator just to spare yearly 1 restart which should cause zero second downtime in a HA environment).

**Comment by primeroz** [comment]
can't really disagree with simplicity and maybe the whole "watch for secret and HUP signal" is a bit too much as you describe.

At the same time though i do believe that supporting the reload when external secret change is an important use case ... even if i don't really know how many people out there are actually using it ( I only know of me and @jurgenweber who implemented it and does not need it since he uses spot instances if i remember correctly). 

I am just afraid that a date based annotation to restart the vault pods in the statefulset will really only work for the internal TLS secret because even if that is a customizable annotation i would have to make it fit the threshold of cert-manager and would be quite hacky. 

I still feel that watching a secret and use that for restarting the vault pods rather than an annotation would be clean an generic since it would work for any secret being an internal or external one , but since this issue is about the Internal one and i understand is a more pressing issue to you guys i might just look into getting a POC for the watch and restart for the external secret and push it for review once this is done ( so i can see how you do trigger the restart )

**Comment by bonifaido** [comment]
Work has been started at: https://github.com/banzaicloud/bank-vaults/tree/tls-renew
