### ISSUE TITLE
Impossible to reinstall the chart in the same namespace twice

### ISSUE THREAD

**Issue by klibr007** [banzaicloud/bank-vaults#1760]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
Hello I'm currently running the bank-vault in a kubernetes cluster that I created in a bare-metal environment. The problem is when I delete the Chart the "vault-unseal-keys" which is a secret resource used to unseal the vault doesn't get deleted. When I reinstall the chart the configurer detects that the secret already exists and doesn't create a new one hich result in the vault not being unsealed.

**Expected behaviour**:
The chart being able to be installed in the same namespace after its uninstallation .

**Steps to reproduce the bug**:
Deploy the chart in a bare-metal environment. Uninstall the chart and reinstall it.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.23.15
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): bare-metal
- bank-vaults version (e.g. 0.4.17): 1.17.0 version of the chart
- Install method (e.g. helm or static manifests): helm install
- Logs from the misbehaving component (and any other relevant logs): 
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by akijakya** [comment]
Hi @klibr007, thank you for using bank-vaults! What I found is that this secret is not being deleted because it is not defined in the chart - it is created by bank-vaults when configured to unseal Vault by itself (this is the default behaviour). One workaround for this I could think of is adding a post-delete hook in the chart to clean up this secret after itself, I am going to make a PR soon and then the solution could be discussed there.

**Comment by klibr007** [comment]
Hi @akijakya thanks for the answer ! It's finally what I did.
