### ISSUE TITLE
[vault-secrets-webhook]: Dynamically update TLS certificates

### ISSUE THREAD

**Issue by fran-wl** [banzaicloud/bank-vaults#1803]
**Is your feature request related to a problem? Please describe.**
The problem I'm facing is that when a certificate used by the vault-secrets-webhook server expires and it's renewed then I need to restart the pods for the server to load the new certificate.

**Describe the solution you'd like**
I would like for certificates to be reloaded without having to restart the vault-secrets-webhook pods.

This could be achieved by overriding the server `TLSConfig.GetCertificate` function so that it reloads the certificate every time it changes. A basic implementation of this feature could be done by changing the line [vault-secrets-webhook/main.go#L134](https://github.com/banzaicloud/bank-vaults/blob/main/cmd/vault-secrets-webhook/main.go#L134) so that the certificate is loaded on every call:
```golang
srv := &http.Server{
	Addr:    listenAddress,
	Handler: mux,
	TLSConfig: &tls.Config{
		GetCertificate: func(*tls.ClientHelloInfo) (*tls.Certificate, error) {
			// TODO: improve to avoid reloading the cert on every call.
			cert, err := tls.LoadX509KeyPair(tlsCertFile, tlsPrivateKeyFile)
			if err != nil {
				return nil, err
			}
			return &cert, nil
		},
	},
}
err = srv.ListenAndServeTLS("", "")
```

**Describe alternatives you've considered**
A more efficient way would be to have a routine to monitor the cert file and reload it once it changes.

**Comment by bonifaido** [comment]
What changes your certificate in the given Secret? People tend to use some kind external tools for this, instead of implementing resource watching in the given application. https://github.com/stakater/Reloader is one of these tools.

Also if you renew the certificate with some CI/CD automation you can simply restart the pods (by default they run in two instances if deployed by the chart) and that causes zero downtime.

**Comment by fran-wl** [comment]
Hi @bonifaido, thanks for taking a look at this. We are using cert-manager to handle changes... We thought it would make sense for this component to be able to keep working by itself without having to rely on other add-ons or do a rollout.

**Comment by rsafonseca** [comment]
@bonifaido bank-vaults already supports configuring cert-manager on it's helm chart (https://github.com/banzaicloud/bank-vaults/tree/main/charts/vault-secrets-webhook#using-cert-manager) but it's an incomplete solution since the pods are unaware of cert-manager's update of the secret. Given this, i think the PR makes a lot of sense to be something that is handled by the application, which will provide it with more robust capabilities to avoid unexpected outages.

**Comment by fran-wl** [comment]
@bonifaido I think that @rsafonseca makes a good point regarding this feature complementing the cert-manager use case. Do you have any concerns regarding implementing resource watching? I think it's pretty similar to what is done by the configure cmd, isn't it?
