### ISSUE TITLE
Missing documentation for mutate-probes annotation

### ISSUE THREAD

**Issue by rfvmonteiro** [banzaicloud/bank-vaults#1874]
There are a documented tip and trick with a solution to [Mutate ENV passed to a liveness or readiness probe](https://banzaicloud.com/docs/bank-vaults/tips-and-tricks/#mutate-env-passed-to-a-liveness-or-readiness-probe) but there are also a not documented annotation in the source code (vault.security.banzaicloud.io/mutate-probes) that seems to trigger the same functionality.

It is something that was forgotten to be documented or there are some concern we need to know about before using that annotation? 

Thank you!

**Comment by akijakya** [comment]
Hi @rfvmonteiro, thanks for using Bank-Vaults, also sorry for the late response.

It is interesting because the [tip and trick](https://github.com/bank-vaults/bank-vaults.dev/pull/32/files) predates the [PR](https://github.com/banzaicloud/bank-vaults/pull/1427) that introduced that annotation, and it seems to me that the only addition of that annotation is that you don't need to put the line `- /vault/vault-env` before all the other commands in the probe. Basically you can switch that line with a line of annotation.

About the state of the documentation: it is on our roadmap to actualise it and make it better, and this is definitely something we need to review! 🙂

**Comment by rfvmonteiro** [comment]
Thank you @akijakya !

Then we should and will rely on annotation.

Keep up the good work 🙂
