### ISSUE TITLE
Clarify / Support default entrypoint with vault webhook

### ISSUE THREAD

**Issue by captncraig** [banzaicloud/bank-vaults#227]
The readme says this about the mutating webhook:

> The command of the container has to be explicitly defined in the resource definition, the container's default ENTRYPOINT and CMD will not work (to overcome this is a work-in-progress).

A brief look at the code, and I really can't say why this would be the case, but I believe you that it is. 

Is there a better explanation to why adding an init container changes the entrypoint of existing primary containers? Is there a milestone or any progress toward working around that limitation? Thanks!

**Comment by bonifaido** [comment]
Hi Craig, this is because the webhook is not just inserting the init-container but also rewrites (or adds if there isn't any) `command` and `args` parameters in the `PodSpec`, directly from the [blog](https://banzaicloud.com/blog/inject-secrets-into-pods-vault/):

> The init-container also changes the command of the container to run vault-env instead of the application directly. vault-env starts up, connects to Vault (using the Kubernetes Auth method, checks that the environment variables have a reference to a value stored in Vault (vault:secret/....) and replaces that with the value read from Vault’s Secret backend. After that, vault-env executes (with syscall.Exec()) the original process, which can use the secret that was originally stored in Vault.

So since we overwrite the "implicit" entrypoint baked in directly to the Docker image of your application, it is required to make it "explicit". I hope this clarifies your question.

**Comment by bonifaido** [comment]
@captncraig Let me know if you have any questions (reopen the issue).
