### ISSUE TITLE
Operator: ignores the DaemonSet resources?

### ISSUE THREAD

**Issue by dennybaa** [banzaicloud/bank-vaults#275]
Not much just glanced through the code and it seems so. Is that right, any reason why?

**Comment by bonifaido** [comment]
Hi Denis, what do you plan to do with Daemonsets? Could you please elaborate?

**Comment by dennybaa** [comment]
First of all I'd like to say that I'm a beginner. To be honest I more likely misinterpret the code...

However in the blog and docs it's told:

> Our mutating admission webhook injects an executable into containers (in a non-intrusive way) inside **Deployments/StatefulSets** which can then request secrets from Vault through special environment variable definitions.

Does this mean that this mean that admission webhook will ignore pods of the the DaemonSet resources? Would you please clarify.

**Comment by bonifaido** [comment]
I see @dennybaa, no problem!

I was confused because you mentioned the operator, however, this feature belongs to the mutating webhook (maybe one day we will merge this two into one, but now they are two separate processes).

Since the blog was written we have changed the code of the mutating webhook, so it mutates all Pods (that needs to be mutated), it doesn't matter if they are provisioned by a Deployment, or DaemonSet or StatefulSet so don't worry! :)

**Comment by bonifaido** [comment]
Please feel free to ask any questions related to the setup, or if you stumble upon documentation issues.

**Comment by dennybaa** [comment]
Yes one more question please, maybe I should put it into a separate issue. But anyways while you are here... Is there any plans to mount vault secretes as a volume (in-memory for example)?

**Comment by bonifaido** [comment]
Yes, there are plans for that, but not currently something that we are working on actively, so a separate issue as a feature request would be fine!

**Comment by bonifaido** [comment]
If you don't mind @dennybaa, I'm closing this issue.

**Comment by dennybaa** [comment]
Totally don't, @bonifaido. Thank's already tried bank-vaults it's great!
