### ISSUE TITLE
Upgrading configurer, what is the best way to perform?

### ISSUE THREAD

**Issue by szymonpk** [banzaicloud/bank-vaults#283]
**Is your feature request related to a problem? Please describe.**
After operator upgrade (image tag change), configurer pod is using the old image.

**Describe the solution you'd like**
Configurer should be redeployed when operator is upgraded.

**Describe alternatives you've considered**
Deleting configurer manually works fine and looks like this process doesn't affect running vault. But it does not change its image tag.

**Comment by szymonpk** [comment]
Looks like the only working solution is to edit vault-configurer deployment.

**Comment by bonifaido** [comment]
Hi @szymonpk! 

Operator upgrade shouldn't change the configurer deployment IMHO, because the configurer is tied to the CRD and not to the operator deployment. Since the version of bank-vaults is defined in the CRD. If that image version changes, then we can redeploy the configurer as well. Currently only the Vault pod gets redeployed if the bank-vaults image version changes, so we need to fix this.

**Comment by szymonpk** [comment]
Yes, sorry, I have noticed it is tied to crd image not to operator's. But the problem stands, configurer deployment isn't updated.

**Comment by bonifaido** [comment]
Yes, it the is still present, I'm pushing a fix for this.

**Comment by bonifaido** [comment]
The fix is under review, thanks for reporting this @szymonpk !
