### ISSUE TITLE
Missleading message if root token is removed

### ISSUE THREAD

**Issue by szymonpk** [banzaicloud/bank-vaults#303]
**Describe the bug**
I am still fairly fresh vault user, today I have got a message during tests of vault HA:

```
vault-1 bank-vaults time="2019-01-25T09:41:01Z" level=warning msg="failed to tell active instance to step down: unable to get key 'vault-root': error getting object for key 'vault-operatorvault-root': NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: <req id>, host id: <host id>"
```

It is a little bit missleading(?), vault works fine, HA is working. Maybe we can rephrase it? Or, maybe it is possible to avoid getting root token after successful vault unseal? I am not very deep into your code.

It is only a warning, I know.

**To Reproduce**
1. Deploy vault in HA setup
2. Remove root token, as advised per official documentation
3. Force active/standby switch be removing current active pod

**Expected behavior**
No error or different message

**Additional context**
- bank-vaults 0.4.5
- vault 1.0.2

**Comment by bonifaido** [comment]
Hi @szymonpk,

currently, bank-vaults expects the root token to be available in the backing key store (let it be Kubernetes Secrets, S3, GCS...), and there is an open issue for making this optional via requesting a new, temporary root token with the help of the unseal keys if needed, please see: https://github.com/banzaicloud/bank-vaults/issues/129

I recently have created a Kanban project board for bank-vaults, and now I just added this issue to the in-progress issues, because it is a frequently requested feature: https://github.com/banzaicloud/bank-vaults/projects/2

**Comment by szymonpk** [comment]
Hmm, ok. I see I broke reconfiguration. I haven't tested this. Well, thanks for fast response, as always! ;-)

**Comment by szymonpk** [comment]
I will close this issue and subscribe to the #129. Sorry for the duplicate.

**Comment by bonifaido** [comment]
Absolutely no problem, thanks! :)
