### ISSUE TITLE
[vault-operator] Example of Vault monitoring using vault-agent sidecar injection with Prometheus Operator chart

### ISSUE THREAD

**Issue by jshrack-ssi** [banzaicloud/bank-vaults#635]
**Is your feature request related to a problem? Please describe.**
I've read the following guidance document employing a custom Consul template to dynamically generate a token to facilitate Prometheus monitoring of Vault: https://github.com/banzaicloud/bank-vaults/blob/6670d4c7b6a7ec3b4d20afe1a3dc2e0ff40f8635/docs/mutating-webhook/howto-ct-prom.md. This seems confusing to me and a bit like overkill. Do we really need to run Consul as a sidecar and use webhook injection? Also, if you create a static image and store it in something like Artifactory it requires private repo authentication which I don't know is supported with annotations. The static method assumed by the current service monitor CRD seems a bit limited and would the token not ultimately expire unless set to an indefinite TTL? 

**Describe the solution you'd like**
A clear guidance document on how to use the *best* method to dynamically obtain a renewable token from Vault for Prometheus monitoring of Vault.

**Describe alternatives you've considered**
I've already tried to use vault-agent, however, the vault container won't start as I suspect the uid/gid is not running as uid 1000/gid 1000. You also have to create a custom service monitor CRD as the bearerTokenFile path is not configurable.

**Additional context**

**Comment by bonifaido** [comment]
Consul is not required at all, actually, we don't run consul in this project at all, just consul-template and we use the Vault part of it only (bad naming I guess in the original project :) ) This is used for getting dynamic secrets into your pods which are usually stored in file format (instead of env vars). 

What you need is vault-agent sidecar, to get and renew a Vault token for Vault metrics. I would suggest [this tutorial](https://medium.com/@mwieczorek/yet-another-vault-monitoring-with-prometheus-blog-post-f525c862baca) in the meanwhile, but yes a complete example would be fine. BearerTokenFile path in the ServiceMonitor is `"/etc/prometheus/secrets/$VAULT_NAME/vault.token"`.

**Comment by bonifaido** [comment]
@jshrack-ssi just created an updated version of the example. You will need the `master` tag currently from the operator once this gets merged.
