### ISSUE TITLE
vault-secrets-webhook: ability to read values from secrets mounted as volume

### ISSUE THREAD

**Issue by LuciferInLove** [banzaicloud/bank-vaults#681]
**Is your feature request related to a problem? Please describe.**
Hello. I have the secret in kubernetes. Values in this secret have a reference to values stored in Vault. vault-secrets-webhook works great when I set values from this secret as env variables, but if I mount secret as volume it doesn't work.

**Describe the solution you'd like**
Values in secrets (and configmaps maybe) mounted as volumes that have a reference to values stored in Vault must be resolved by vault-secrets-webhook.

**Comment by pbalogh-sa** [comment]
@LuciferInLove Thanks for reporting this. We will check it as soon as possible.

**Comment by pbalogh-sa** [comment]
@LuciferInLove I tested the secret mutation, and it worked for me.
Is the data mutated in your secret?

**Comment by LuciferInLove** [comment]
Sorry please, I've made a mistake in target pod. Thank you for testing.

**Comment by Jude188** [comment]
I'm struggling to get this to work. I'm trying to mount a secret with TLS certs from Vault but can't seem to work out how to check if they're being resolved. A small pointer in the right direction to at least check if they're being resolved would be helpful. When I exec into the pod the contents of the files has not been resolved but running `vault-env env` does correctly resolve other env variables.

**Comment by pbalogh-sa** [comment]
@Jude188  If you want to mount the secret, first you 'll have to mutate the secret you use. In this case, you have to use the secret mutation feature and not the pod the mutation feature. 
https://github.com/banzaicloud/bank-vaults/blob/master/deploy/test-secret.yaml

Security point of view you'd better use pod mutation with `envFrom`
https://github.com/banzaicloud/bank-vaults/tree/master/docs/mutating-webhook

**Comment by saiDevkar** [comment]
I created a secret as following:
`apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: "http://vault.default.svc.cluster.local:8200"
    vault.security.banzaicloud.io/vault-role: "sample"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2YXVsdDpzZWNyZXQvZGF0YS9kb2NrZXJyZXBvI0RPQ0tFUl9SRVBPX1VTRVIiLCJwYXNzd29yZCI6InZhdWx0OnNlY3JldC9kYXRhL2RvY2tlcnJlcG8jRE9DS0VSX1JFUE9fUEFTU1dPUkQiLCJhdXRoIjoiZG1GMWJIUTZjMlZqY21WMEwyUmhkR0V2Wkc5amEyVnljbVZ3YnlORVQwTkxSVkpmVWtWUVQxOVZVMFZTT25aaGRXeDBPbk5sWTNKbGRDOWtZWFJoTDJSdlkydGxjbkpsY0c4alJFOURTMFZTWDFKRlVFOWZVRUZUVTFkUFVrUT0ifX19
  vaultdata: dmF1bHQ6c2VjcmV0L2RhdGEvYWNjb3VudHMvYXdzI0FXU19BQ0NFU1NfS0VZX0lE`

and created a deployment as following:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets
  template:
    metadata:
      labels:
        app: hello-secrets
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://vault.default.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-role: "sample"
    spec:
      serviceAccountName: default
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "cat /var/my-app/vaultdata && echo going to sleep... && sleep 10000"]
        volumeMounts:
            - mountPath: "/var/my-app"
              name: vault-secret
      volumes:
        - name: vault-secret
          secret:
                secretName: sample-secret`
and in the logs of the pod it displays the reference value _vault:secret/data/accounts/aws#AWS_ACCESS_KEY_ID_ instead of the actual vault secret.

But if I pass the Kubernetes Secret to ENV using valueFrom it works fine and displays the actual vault secret in container's env variable.

I need to refer the Vault secret using the secret mount as volume, Am I missing something here?

**Comment by bonifaido** [comment]
When you created the sample-secret it should have been populated with data from Vault, if it is not the case, you should check the logs of the webhook instances to see what went wrong.

**Comment by saiDevkar** [comment]
@bonifaido Thanks for the quick response. I'll check the suggested steps and let here know if anything is went wrong.

**Comment by alunsford** [comment]
@saiDevkar were you able to get this working? We're running into the exact same scenario: the secret is populated into the environment variable, but not the file mounted through the `volumeMount` and `volumes` definitions.

**Comment by selmison** [comment]
In this case, I think using [vault templating](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/vault-agent-templating/) or [consul-template](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/consul-template/) is a good option.
