### ISSUE TITLE
Override Vault Default TLS Parameters (CA, Cert, and Private Key)

### ISSUE THREAD

**Issue by theonewolf** [banzaicloud/bank-vaults#781]
**Is your feature request related to a problem? Please describe.**
I have tried changing the default certificate and key to custom ones.  The Vault instances fail to initialize, I believe because the Vault commands no longer know the proper CA Root Certificate to use.

**Describe the solution you'd like**
I would like to be able to override the environment variable `VAULT_CACERT`, or have some other method of specifying the secret to use for certificates in the system.

Perhaps being able to replace the `vault-tls` secret with a `cert-manager` generated secret would work much better.

**Describe alternatives you've considered**
Since `vault-tls` secrets and use of `VAULT_CACERT` appear hardcoded, I don't see an easy alternative.

**Additional context**
N/A

**Comment by primeroz** [comment]
the whole operator rely on being able to manage the vault-tls secret. while not impossible to override it i don't think is the best way to achieve what you are trying to do.

In order to use cert-manager secret ( or any other external secret ) you would be better off using multiple listeners , see [this](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-customports.yaml) example here

in a nutshell
* Have cert-manager create a secret
* Reference the secret in the volumes and volume mounts of the vault crd
* have multiple listeners , one of the using the cert-manager secret ( not the 8200 possibly )
* have an ingress / node port / whatever to expose that listener externally if needed

I use this setup successfully on multiple clusters 

In general i would recommend you to join the slack channel for this kind of questions since you would get an answer much quicker

**Comment by theonewolf** [comment]
@primeroz this isn't really a question, I would like this fundamental limit removed from the product.  If we won't consider this, then we can close with a WONTFIX type status.

It is difficult to impossible to pass audits and achieve compliance if we can't control:

- Bit lengths of keys
- Encryption algorithms in use
- Potentially other parameters

Having a port configured for application software / Vault where we can't easily change security parameters is not ideal.

I understand your workaround, and thanks for linking the configuration file.  We were looking at that, but didn't want two ports open to achieve this.

**Comment by primeroz** [comment]
@theonewolf my bad, i did not understand it was like that :)

Looking at it if you pre-create a `vault-tls` secret with the same format as the one that the operator would create i believe it will work as long as all the fields are populated ( ca.crt , server.crt and server.key ) but it might start to fail when the operator thinks it is time to renew it ( https://github.com/banzaicloud/bank-vaults/blob/d0b151f2d1afd3c7e1c6cc4f688e73bf177f7792/operator/pkg/controller/vault/vault_controller.go#L327 ) 

So overall yeah, this is something that should be implemented as a feature flag / settings , will leave it to the team :)

**Comment by bonifaido** [comment]
I'm really open to a proposal how to do this properly, so the project could pass security audits as well! I think the current automatically generating behavior with more configuration, and a user provided cert version should be sufficient enough.

**Comment by theonewolf** [comment]
@bonifaido I agree with you; I was actually going to take the approach close to what @primeroz is saying---trying to replace / overwrite your `vault-tls`.  I suppose the problem there that we run into is multi-writers during certificate lifecycle events.

If we have agreement on the CR spec, then I think it's OK to let the user specify the secret for it.  As long as we could get lifecycle events to be properly handled (I think that is supposed to happen with the `cert-manager` approach as described in the examples---it watches the secret).  I think the operator would just be "hands off" and only a "reader" of the certificates then?

Although, I haven't seen everything that you do with your CA.  If you have other operations (other managed certificates other than `vault-tls`) I haven't investigated the impact to them yet.

Some of our enterprise clients actually require us to use _their_ PKI solution---they issue certificates.  We can automate it, but we have to be able to configure our software stack.

**Comment by primeroz** [comment]
@bonifaido with the new feature from https://github.com/banzaicloud/bank-vaults/pull/859 is the `cert-manager` cent of renewing the certificate handled by the operator ? 

This would be great to replace my current setup with 2 listeners but since i use public let's encrypt certificate that get refreshed every 2 months i definetely need the operator to notice the certificate was updated and the statefulset reloaded

**Comment by pbalogh-sa** [comment]
@primeroz When existing TLS secret is set, the operator certificate renewal mechanism is turned off .

**Comment by primeroz** [comment]
@pbalogh-sa thanks. Would you consider adding the same annotation based control to the external one by
- detect the expiration date has changed
- update annotation
- trigger reload ?

**Comment by pbalogh-sa** [comment]
@primeroz Good idea. I'll implement it soon. Thanks.

**Comment by bonifaido** [comment]
We did something similar with https://github.com/banzaicloud/bank-vaults/tree/master/docs/external-secrets don't we?
